---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.10
  driver_config:
    box: opscode-ubuntu-12.10
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.10_provisionerless.box
  run_list: ["recipe[apt]"]

- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list: ["recipe[apt]"]

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list: ["recipe[apt]"]

- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[backslasher-python]
  - recipe[backslasher_python_test::cook-3084]
  attributes: {}
- name: pip
  run_list:
  - recipe[minitest-handler]
  - recipe[backslasher-python]
  - recipe[backslasher_python_test::test_pip]
- name: exert
  excludes: ["centos-5.9"]
  run_list:
  - recipe[backslasher-python]
  - recipe[backslasher_python_test::test_exert]
- name: virtualenv
  run_list:
  - recipe[backslasher-python]
  - recipe[backslasher_python_test::test_virtualenv]
