---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list: ["recipe[apt]"]
- name: centos-6.7
- name: centos-6.7-chef-12.04
  driver:
    box: opscode-centos-6.7
  provisioner:
    require_chef_omnibus: 12.04
- name: centos-7.1

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[backslasher-python]
  - recipe[backslasher_python_test::cook-3084]
  attributes: {}
- name: pip
  run_list:
  - recipe[minitest-handler]
  - recipe[backslasher-python]
  - recipe[backslasher_python_test::test_pip]
  - recipe[backslasher_python_test::test_pip_owner]
- name: exert
  excludes: ["centos-5.9"]
  run_list:
  - recipe[backslasher-python]
  - recipe[backslasher_python_test::test_exert]
- name: virtualenv
  run_list:
  - recipe[backslasher-python]
  - recipe[backslasher_python_test::test_virtualenv]
