sudo: required
dist: trusty
services:
  - docker

language: ruby
rvm: 2.3.1
cache: bundler
script:
  - bundle install --with=testing && bundle exec rake testing:travis
  - bundle install --with=kitchen && kitchen_driver=docker bundle exec rake testing:kitchen
